<?php echo $this->doctype(); ?>



<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Pop ' . $this->translate('Serizator'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/famico.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>


        <script src="<?php echo $this->basePath('http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('js/menuPanda.min.js') ?>"></script>
        <link  rel="stylesheet" href="<?php echo $this->basePath('css/mpDefaultSkin.css') ?>">
        </link>
        <link  rel="stylesheet" href="<?php echo $this->basePath('css/style.css') ?>">
        </link>

        <script type="text/javascript">
            $(document).ready(function() {
                $("#menu").pandfy();
            });
        </script>



    </head>

    <body>
        <nav id="menu"> 

            <ul data-title="Menu"  >   


                <!--the LI element are horizontal (or normal) links... -->

                <li><a href="http://localhost/bouland/public/serie">Mes series</a></li>
                <li><a href="http://localhost/bouland/public/serie/add">Ajouter une série</a></li>

                <li><a href="http://localhost/bouland/public">A propos</a></li>

            </ul>


        </nav>  



        <div  $.fn.moveTo = function(selector){
            return this.each(function(){
            var cl = $(this).clone();
            $(cl).appendTo(selector);
            $(this).remove();
            });
            };id="reallyBigDiv">

            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo-cinema.png') ?>" alt="logo"/>&nbsp<?php echo $this->translate('Serizator !') ?></a>


                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">



                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </nav>


            <div id="test5">
                <div class="container">
                    <div id="menubutton">
                        <img src="<?php echo $this->basePath('img/menuPanda_menu.png') ?>"  class="mp-buttom" width="80" height="80"  />
                    </div>
                    <?php //echo $this->navigation('navigation')->menu(); ?>
                    <div class="test2">
                        <?php echo $this->content; ?>
                    </div>
                    <footer>
                        <p>Bouland Joris & Le Brech Florian - <?php echo date('Y') ?> </p>
                    </footer>
                </div> <!-- /container -->
            </div>
            <?php echo $this->inlineScript() ?>





    </body>
</html>