<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Bienvenue sur %sSerizator%s !'), '<span class="zf-red">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate("L'outil de gestion de serie en ligne, actuellement en beta fermée."))  ?></p>
</div>

<div class="row">

    <p>Réalisé avec Zend Framework 2 par Joris Bouland & Florian Le Brech, pour le cours de Projet Web.<p>
</div>
